# Generated by Django 4.2 on 2024-05-30 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("teachinghour", models.IntegerField()),
                ("tutor", models.CharField(max_length=200)),
            ],
        ),
    ]
